export const Mitglieder = [
  {
    Vorname: "Isabella",
    Nachname: "Rossi",
    Kontostand: 16.79,
    Alter: 28,
    Postleitzahl: 90018,
    Mafiagruppe: "Cosa Nostr",
    ID: 3,
  },
  {
    Vorname: "Marco",
    Nachname: "Santoro",
    Kontostand: 78.63,
    Alter: 46,
    Postleitzahl: 90120,
    Mafiagruppe: "Cosa Nostr",
    ID: 6,
  },
  {
    Vorname: "Roberto",
    Nachname: "Amato",
    Kontostand: 89.01,
    Alter: 48,
    Postleitzahl: 90120,
    Mafiagruppe: "Cosa Nostr",
    ID: 10,
  },
  {
    Vorname: "Salvatore",
    Nachname: "Martino",
    Kontostand: 67.54,
    Alter: 44,
    Postleitzahl: 90034,
    Mafiagruppe: "Cosa Nostr",
    ID: 12,
  },
  {
    Vorname: "Angela",
    Nachname: "Greco",
    Kontostand: 84.56,
    Alter: 32,
    Postleitzahl: 90034,
    Mafiagruppe: "Cosa Nostr",
    ID: 16,
  },
  {
    Vorname: "Maria",
    Nachname: "Ferrara",
    Kontostand: 41.59,
    Alter: 48,
    Postleitzahl: 90034,
    Mafiagruppe: "Cosa Nostr",
    ID: 20,
  },
  {
    Vorname: "Isabelle",
    Nachname: "DeSantis",
    Kontostand: 37.12,
    Alter: 41,
    Postleitzahl: 90120,
    Mafiagruppe: "Cosa Nostr",
    ID: 22,
  },
  {
    Vorname: "Angelo",
    Nachname: "Russo",
    Kontostand: 51.78,
    Alter: 47,
    Postleitzahl: 90045,
    Mafiagruppe: "Cosa Nostr",
    ID: 29,
  },
];

export const Waffen = [
  {
    WaffenID: 15,
    Name: "Baseballschläger",
    Staerke: 5,
    Besitzer: "Luca DeLucca",
    Preis: 10,
  },
  {
    WaffenID: 3,
    Name: "Baseballschläger",
    Staerke: 5,
    Besitzer: "Händler",
    Preis: 20,
  },
  {
    WaffenID: 9,
    Name: "Baseballschläger",
    Staerke: 5,
    Besitzer: "Giovanni Morelli",
    Preis: 25,
  },
  {
    WaffenID: 20,
    Name: "Messer",
    Staerke: 4,
    Besitzer: "Valentina Marino",
    Preis: 30,
  },
  {
    WaffenID: 19,
    Name: "Axt",
    Staerke: 7,
    Besitzer: "Mario Ricci",
    Preis: 45,
  },
  {
    WaffenID: 21,
    Name: "Baseballschläger",
    Staerke: 5,
    Besitzer: "Händler",
    Preis: 65,
  },
  {
    WaffenID: 13,
    Name: "Axt",
    Staerke: 7,
    Besitzer: "Francesca Valenti",
    Preis: 70,
  },
  {
    WaffenID: 1,
    Name: "Axt",
    Staerke: 7,
    Besitzer: "Giovanni Russo",
    Preis: 75,
  },
  {
    WaffenID: 7,
    Name: "Axt",
    Staerke: 7,
    Besitzer: "Roberto Amato",
    Preis: 80,
  },
  {
    WaffenID: 8,
    Name: "Messer",
    Staerke: 4,
    Besitzer: "Händler",
    Preis: 90,
  },
  {
    WaffenID: 25,
    Name: "Axt",
    Staerke: 7,
    Besitzer: "Maria Ferrara",
    Preis: 90,
  },
  {
    WaffenID: 14,
    Name: "Messer",
    Staerke: 4,
    Besitzer: "Antonio Falcone",
    Preis: 105,
  },
  {
    WaffenID: 2,
    Name: "Messer",
    Staerke: 4,
    Besitzer: "Valentina Marino",
    Preis: 110,
  },
  {
    WaffenID: 18,
    Name: "Gewehr",
    Staerke: 10,
    Besitzer: "Händler",
    Preis: 140,
  },
  {
    WaffenID: 22,
    Name: "Pistole",
    Staerke: 8,
    Besitzer: "Salvatore Martino",
    Preis: 230,
  },
  {
    WaffenID: 4,
    Name: "Pistole",
    Staerke: 8,
    Besitzer: "Salvatore Martino",
    Preis: 320,
  },
  {
    WaffenID: 10,
    Name: "Pistole",
    Staerke: 8,
    Besitzer: "Händler",
    Preis: 410,
  },
  {
    WaffenID: 16,
    Name: "Pistole",
    Staerke: 8,
    Besitzer: "Händler",
    Preis: 560,
  },
  {
    WaffenID: 6,
    Name: "Gewehr",
    Staerke: 10,
    Besitzer: "Sofia Ferraro",
    Preis: 590,
  },
  {
    WaffenID: 5,
    Name: "Shotgun",
    Staerke: 9,
    Besitzer: "Händler",
    Preis: 650,
  },
  {
    WaffenID: 11,
    Name: "Shotgun",
    Staerke: 9,
    Besitzer: "Händler",
    Preis: 680,
  },
  {
    WaffenID: 17,
    Name: "Shotgun",
    Staerke: 9,
    Besitzer: "Angelo Russo",
    Preis: 700,
  },
  {
    WaffenID: 24,
    Name: "Gewehr",
    Staerke: 10,
    Besitzer: "Händler",
    Preis: 750,
  },
  {
    WaffenID: 23,
    Name: "Shotgun",
    Staerke: 9,
    Besitzer: "Händler",
    Preis: 900,
  },
  {
    WaffenID: 12,
    Name: "Gewehr",
    Staerke: 10,
    Besitzer: "Isabella Rossi",
    Preis: 900,
  },
];

export const Gruppen = [
  { Name: "Cosa Nostra", Anfuehrer: "Salvatore Martino", Gebietsanteil: 25 },
  { Name: "Camorra", Anfuehrer: "Giovanni Russo", Gebietsanteil: 35 },
  { Name: "Ndrangheta", Anfuehrer: "Matteo Esposito", Gebietsanteil: 40 },
];

export default {
  Mitglieder,
  Waffen,
  Gruppen,
};
